# Generated by Django 4.0.3 on 2023-06-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_automobilevo_import_href_automobilevo_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='sold_on_date',
        ),
        migrations.AddField(
            model_name='sales',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
