# Generated by Django 4.0.3 on 2023-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_sales_sold_on_date_sales_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
